### ISSUE TITLE
Presta V1.7.x compatibility? 

### ISSUE THREAD

**Issue by ramb0t** [Payfast/mod-prestashop_1_7#2]
Any testing done on 1.7.x at at all?
Plans to update this module to support the new version of Prestashop?

**Comment by Brendon-P** [comment]
Hi
The module for PrestaShop 1.7 is available [here](https://github.com/PayFast/mod-prestashop_1_7). Should you require any further assistance please submit a ticket to support@payfast.co.za

Thank you.
The PayFast Team
